# Use a lightweight Python base image
FROM python:alpine AS baseapi

# Set environment variables
ENV POETRY_VERSION=1.6.1 \
    PYTHONUNBUFFERED=1 \
    POETRY_NO_INTERACTION=1

# # Install system dependencies
# RUN apk add --no-cache gcc musl-dev libffi-dev python3-dev curl openssl

# Install Poetry
RUN pip install --no-cache-dir "poetry==$POETRY_VERSION"

# Set the working directory
WORKDIR /gfiletosqlite

# Copy all files
COPY . ./

# Install dependencies with Poetry
RUN poetry install --no-root

# Expose the port for FastAPI
EXPOSE 8800

# Command to run the application
CMD ["poetry", "run", "python", "./src/main.py"]